services:
  rabbitmq:
    image: rabbitmq:4.3.2-management-alpine
    container_name: my-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    entrypoint: >
      sh -c "
      rabbitmq-server & 
      rabbitmqctl wait /var/run/rabbitmq/pid; 
      rabbitmqctl add_vhost /choreography; 
      rabbitmqctl add_vhost /orchestration; 
      wait"
    networks:
      - my-global-network

  order-db:
    image: postgres:18-alpine
    container_name: order-db
    ports:
      - "5433:5432"
    env_file:
      - "order/.env"
    volumes:
      - order-db-data:/var/lib/postgresql/18/data
    networks:
      - my-global-network

  payment-db:
    image: postgres:18-alpine
    container_name: payment-db
    ports:
      - "5434:5432"
    env_file:
      - "payment/.env"
    volumes:
      - payment-db-data:/var/lib/postgresql/18/data
    networks:
      - my-global-network

  inventory-db:
    image: postgres:18-alpine
    container_name: inventory-db
    ports:
      - "5435:5432"
    env_file:
      - "inventory/.env"
    volumes:
      - inventory-db-data:/var/lib/postgresql/18/data
    networks:
      - my-global-network

networks:
  my-global-network:
    driver: bridge
    external: true

volumes:
  order-db-data:
  payment-db-data:
  inventory-db-data:
