services:
  rabbitmq:
    image: rabbitmq:4.3.2-management-alpine
    container_name: my-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-global-network

  order-db:
    image: postgres:18-alpine
    container_name: order-db
    ports:
      - "5433:5432"
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: ${ORDER_USER}
      POSTGRES_PASSWORD: ${ORDER_PASSWORD}
      POSTGRES_DB: ${ORDER_DB}
    volumes:
      - order-db-data:/var/lib/postgresql/18/data
    networks:
      - my-global-network

  payment-db:
    image: postgres:18-alpine
    container_name: payment-db
    ports:
      - "5434:5432"
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: ${PAYMENT_USER}
      POSTGRES_PASSWORD: ${PAYMENT_PASSWORD}
      POSTGRES_DB: ${PAYMENT_DB}
    volumes:
      - payment-db-data:/var/lib/postgresql/18/data
    networks:
      - my-global-network

  inventory-db:
    image: postgres:18-alpine
    container_name: inventory-db
    ports:
      - "5435:5432"
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: ${INVENTORY_USER}
      POSTGRES_PASSWORD: ${INVENTORY_PASSWORD}
      POSTGRES_DB: ${INVENTORY_DB}
    volumes:
      - inventory-db-data:/var/lib/postgresql/18/data
    networks:
      - my-global-network

networks:
  my-global-network:
    name: my-global-network
    driver: bridge

volumes:
  order-db-data:
  payment-db-data:
  inventory-db-data:
