spring:
  application:
    name: order
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
  datasource:
    url: ${ORDER_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: ${RABBITMQ_HOST}
    virtual-host: ${SPRING_RABBITMQ_VHOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    order:
      created:
        payment:
          queue: ${ORDER_CREATED_PAYMENT_QUEUE}
        inventory:
          queue: ${ORDER_CREATED_INVENTORY_QUEUE}
        exchange: ${ORDER_CREATED_EXCHANGE}
        routingKey: ${ORDER_CREATED_ROUTINGKEY}
      status:
        check:
          queue: ${ORDER_STATUS_CHECK_QUEUE}
          exchange: ${ORDER_STATUS_CHECK_EXCHANGE}
          routingKey: ${ORDER_STATUS_CHECK_ROUTINGKEY}
    payment:
      charged:
        queue: ${PAYMENT_CHARGED_QUEUE}
      failed:
        order:
          queue: ${PAYMENT_FAILED_ORDER_QUEUE}
    inventory:
      reserved:
        queue: ${INVENTORY_RESERVED_QUEUE}
      failed:
        order:
          queue: ${INVENTORY_FAILED_ORDER_QUEUE}

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4317

server:
  port: 8080
