spring:
  application:
    name: order
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/choreography
    username: order_san_123_#
    password: order_sama_789_!
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    order:
      created:
        queue: order.created.queue
        exchange: order.created.exchange
        routingKey: order.created.routingkey

server:
  port: 8080
